gooutside/gooutside/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


# customize admin site
admin.site.site_header = "Go Outside Administration"
admin.site.site_title = "Go Outside Admin"


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('places.urls', namespace='places')),
]


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

gooutside/places/urls.py
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns

from . import views


app_name = 'places'

urlpatterns = [
    path('', views.PlacesView.as_view(), name='places'),
    path('categories/', views.PlaceCategoryList.as_view(), name='category_list'),
    path('attributes/', views.PlaceAttributeList.as_view(), name='attribute_list'),
    path('sources/', views.PlaceSourceList.as_view(), name='source_list'),
    path('places/', views.PlaceList.as_view(), name='place_list'),
]


urlpatterns = format_suffix_patterns(urlpatterns)

gooutside/places/models.py
from django.contrib.gis.db import models

from localflavor.us.models import USStateField


class PlaceCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class PlaceAttribute(models.Model):
    name = models.CharField(max_length=128, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class PlaceSource(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=255, blank=True)
    url = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        unique_together = [('name', 'url')]

    def __str__(self):
        return self.name


class Place(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(PlaceCategory, on_delete=models.CASCADE)

    location = models.PointField()
    state = USStateField()

    attributes = models.ManyToManyField(PlaceAttribute, blank=True)

    source = models.ForeignKey(PlaceSource, on_delete=models.CASCADE)
    source_identification = models.CharField(max_length=64, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['state', 'name']
        unique_together = [('source', 'source_identification')]

    def __str__(self):
        return self.name


class PlaceSourceInterfaceMapping(models.Model):
    key = models.CharField(max_length=255, help_text="feature['a']['b'] becomes a__b")
    rule = models.CharField(max_length=255, help_text='lambda x: [fill this in]')
    success = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return f"Mapping key: {self.key}; rule: {self.rule}"

    def get_key_str(self):
        return "".join([f"['{k}']" for k in self.key.split('__')])

    def get_rule(self):
        return lambda x: eval(self.rule)

    def evaluate_mapping(self, json_object):
        try:
            rule_function = self.get_rule()
            raw_value = eval(f"json_object{self.get_key_str()}")
            processed_value = rule_function(raw_value)
            if self.success:
                if processed_value:
                    return self.success
                else:
                    return ""
            else:
                return processed_value
        except:
            return ""


class PlaceSourceInterface(models.Model):
    source = models.OneToOneField(PlaceSource, on_delete=models.CASCADE)

    json_url = models.URLField()

    coord_type = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='coord_type')

    place_list = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='place_list')

    name_primary = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='name_primary')
    name_secondary = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.SET_NULL, blank=True, null=True, related_name='name_secondary')

    category_mappings = models.ManyToManyField(PlaceSourceInterfaceMapping, related_name='category_mappings')

    public = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='public')

    location = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='location')
    location_lat = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, blank=True, null=True, related_name='location_lat')
    location_lng = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, blank=True, null=True, related_name='location_lng')

    state = USStateField()

    attribute_mappings = models.ManyToManyField(PlaceSourceInterfaceMapping, blank=True, related_name='attribute_mappings')

    source_identification = models.OneToOneField(PlaceSourceInterfaceMapping, on_delete=models.CASCADE, related_name='source_identification')

    def __str__(self):
        return f"Interface for {self.source}"

gooutside/places/views.py
from django.conf import settings
from django.views.generic import TemplateView

from rest_framework.filters import SearchFilter
from rest_framework import generics

from django_filters.rest_framework import DjangoFilterBackend

from localflavor.us.us_states import STATE_CHOICES

from .models import PlaceCategory, PlaceAttribute, PlaceSource, Place
from .serializers import (
    PlaceCategorySerializer, PlaceAttributeSerializer,
    PlaceSourceSerializer, PlaceSerializer,
)
from .filters import PlaceFilter


class PlacesView(TemplateView):
    template_name = 'places/places.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['states'] = STATE_CHOICES

        context['google_maps_api_key'] = getattr(settings, 'GOOGLE_MAPS_API_KEY', '')

        return context


class PlaceCategoryList(generics.ListAPIView):
    queryset = PlaceCategory.objects.all()
    serializer_class = PlaceCategorySerializer


class PlaceAttributeList(generics.ListAPIView):
    queryset = PlaceAttribute.objects.all()
    serializer_class = PlaceAttributeSerializer


class PlaceSourceList(generics.ListAPIView):
    queryset = PlaceSource.objects.all()
    serializer_class = PlaceSourceSerializer


class PlaceList(generics.ListAPIView):
    queryset = Place.objects.all()
    serializer_class = PlaceSerializer
    filter_class = PlaceFilter
    filter_backends = (SearchFilter, DjangoFilterBackend)
    search_fields = ('name',)

    def filter_queryset(self, queryset):
        filtered = super().filter_queryset(queryset)

        # TODO https://stackoverflow.com/a/8637972/5286674
        if 'attributes[]' in self.request.query_params:
            filtered = filtered.filter(attributes__in=self.request.query_params.getlist('attributes[]'))

        return filtered

gooutside/places/templates/places/base.html
<!DOCTYPE html> {% load static compress %}
<html>

<head>
  <meta charset="utf-8">

  <link rel="shortcut icon" type="image/png" href="{% static 'places/images/favicon.png' %}">

  <title>Go Outside</title>

  {% compress css %}
    <link rel="stylesheet" href="{% static 'places/bootstrap-4.1.0/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'places/css/bootstrap.theme.css' %}">
    <link rel="stylesheet" href="{% static 'places/css/global.css' %}">
    {% block styles %}{% endblock %}
  {% endcompress %}

  {% if google_analytics %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ google_analytics }}');
    </script>
  {% endif %}

  <!-- Developed by kjpc-tech (https://kjpc.tech/developerlink/) -->
</head>

<body>
  <header class="bg-light text-dark border-bottom border-info py-4 mb-4">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1>Go Outside</h1>
        </div>
      </div>
    </div>
  </header>

  <main>
    {% block content %}{% endblock %}
  </main>

  <footer  class="bg-dark text-light border-top border-info py-4 mt-4">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <p class="m-0">Use at your own risk. Please contact local agencies for accurate and up-to-date information regarding land use.</p>
          <p class="mt-2"><small>The information provided on this website is <a href="https://hub.arcgis.com/pages/open-data" target="_blank">Open Data</a> from <a href="https://hub.arcgis.com/" target="_blank">ArcGIS Hub</a>.</small></p>
        </div>
      </div>

      <div class="row">
        <div class="col-12 text-center small">
          <a class="mr-lg-4" href="#" data-toggle="modal" data-target="#tos-modal">Terms of Service</a>
          <a class="mr-lg-4" href="https://gitlab.com/kjpc-tech/go-outside" target="_blank">Source Code</a>
          <a class="mr-lg-4" href="https://gitlab.com/kjpc-tech/go-outside#adding-more-places" target="_blank">Adding More Places</a>
          <a href="https://kjpc.tech/developerlink/" target="_blank">Developer</a>
        </div>
      </div>
    </div>
  </footer>

  <div class="modal" id="tos-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Terms of Service</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <div class="modal-body">
          <p>The information provided on this website is provided "as is", with no warranties of any kind. In no event shall the developer be liable for any claim, damages or other liability due to the use or misuse of this website in any way.</p>
          <p>This website is intended to be a help in providing public land access information to the website users. It is the responsibility of the website user to verify that the information is accurate with local agencies before using the land.</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  {% compress js %}
    <script src="{% static 'places/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'places/bootstrap-4.1.0/js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
  {% endcompress %}
  {% block scripts-uncompressed %}{% endblock %}
</body>

</html>

gooutside/places/templates/places/places.html
{% extends "places/base.html" %}

{% load static %}

{% block styles %}
  <link href="{% static 'places/css/places.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container" id="app">
    <div class="row">
      <div class="col-lg-4 mb-4 mb-lg-0">
        <select class="form-control" name="category" v-model="category">
          <option value="all">All Categories</option>
          <option v-for="option in categories" v-bind:value="option.id">
            (( option.name ))
          </option>
        </select>
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <select class="form-control" name="state" v-model="state">
          <option value="all">All States</option>
          {% for value, display in states %}
            <option value="{{ value }}">
              {{ display }}
            </option>
          {% endfor %}
        </select>
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <input type="text" class="form-control" name="search" placeholder="Search" v-model="search">
      </div>
    </div>

    <div class="row border-bottom border-success pb-4 my-4">
      <div class="col-12">
        <div class="form-check form-check-inline mx-3" v-for="option in attributes">
          <input type="checkbox" class="form-check-input m-0" name="attributes" v-bind:id="'attribute-' + option.id" v-bind:value="option.id" v-on:click="adjust_attributes">
          <label class="form-check-label p-0" v-bind:for="'attribute-' + option.id">(( option.name ))</label>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div id="map" ref="map"></div>
      </div>
    </div>

    <div id="place_info" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title"><span v-if="current_place_index != null">(( places[current_place_index].name ))</span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <snap aria-hidden="true">&times;</snap>
            </button>
          </div>

          <div class="modal-body">
            <div class="container-fluid" v-if="current_place_index != null">
              <div class="row">
                <div class="col-12">
                  <p><span class="text-muted">Category:</span> (( categories_by_key[places[current_place_index].category].name ))</p>
                  <p><span class="text-muted">Attributes:</span></p>
                  <ul>
                    <li v-for="attr in places[current_place_index].attributes">(( attributes_by_key[attr].name ))</li>
                  </ul>
                  <p><span class="text-muted">Source:</span> (( sources_by_key[places[current_place_index].source].name ))</p>
                </div>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <input ref="category_list_url" type="hidden" v-model="category_list_url" data-default="{% url 'places:category_list' %}">
    <input ref="attribute_list_url" type="hidden" v-model="attribute_list_url" data-default="{% url 'places:attribute_list' %}">
    <input ref="source_list_url" type="hidden" v-model="source_list_url" data-default="{% url 'places:source_list' %}">
    <input ref="place_list_url" type="hidden" v-model="place_list_url" data-default="{% url 'places:place_list' %}">
  </div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'places/js/vue.min.js' %}"></script>
  <script src="{% static 'places/js/vue-resource.min.js' %}"></script>
  <script src="{% static 'places/js/places.js' %}"></script>
{% endblock %}
{% block scripts-uncompressed %}
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=init_map"></script>
{% endblock %}